// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCjyumqGVvqKV01sn33_f_Bmt0QXmktiU',
    appId: '1:798183049780:web:7edca781a973f7037e9861',
    messagingSenderId: '798183049780',
    projectId: 'sonia-app-26f13',
    authDomain: 'sonia-app-26f13.firebaseapp.com',
    storageBucket: 'sonia-app-26f13.firebasestorage.app',
    measurementId: 'G-QER2LSF5XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH455r43Fmkrkc8ZqBIbM1daEBKnniJbM',
    appId: '1:798183049780:android:36dcea02203afe677e9861',
    messagingSenderId: '798183049780',
    projectId: 'sonia-app-26f13',
    storageBucket: 'sonia-app-26f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCciNOuxJr_RuvyBTKK_5zESde4j12za70',
    appId: '1:798183049780:ios:deb6e1db88e21ad17e9861',
    messagingSenderId: '798183049780',
    projectId: 'sonia-app-26f13',
    storageBucket: 'sonia-app-26f13.firebasestorage.app',
    iosBundleId: 'com.lwm.soniaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCciNOuxJr_RuvyBTKK_5zESde4j12za70',
    appId: '1:798183049780:ios:deb6e1db88e21ad17e9861',
    messagingSenderId: '798183049780',
    projectId: 'sonia-app-26f13',
    storageBucket: 'sonia-app-26f13.firebasestorage.app',
    iosBundleId: 'com.lwm.soniaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCjyumqGVvqKV01sn33_f_Bmt0QXmktiU',
    appId: '1:798183049780:web:a16fc6545377dd9f7e9861',
    messagingSenderId: '798183049780',
    projectId: 'sonia-app-26f13',
    authDomain: 'sonia-app-26f13.firebaseapp.com',
    storageBucket: 'sonia-app-26f13.firebasestorage.app',
    measurementId: 'G-44LPK1G7F9',
  );
}
